kind: pipeline
name: default

steps:
- name: Debian
  image: plugins/docker
  settings:
    repo: chrishsieh/php-apache-dev
    dockerfile: ./Debian/Dockerfile
    context: ./Debian
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - debian-latest
      - latest
